apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  description: Python app that display time - name ${{values.app_name}}
  annotations:
    github.com/project-slug: JohnMonteir0/${{values.app_name}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: devops
  lifecycle: experimental